version: "3.7"
services:
  extractor:
    container_name: extractor
    restart: always
    image: happysession/extractor
    # build: ../extractor
    depends_on:
      - mongo
  api:
    container_name: api
    restart: always
    image: happysession/api
    # build: ../api
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/happy --quiet
      interval: 5s
      timeout: 5s
      retries: 12
